# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0003_auto_20161225_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('canvassHours', models.IntegerField()),
                ('otherHours', models.IntegerField()),
                ('trf', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
