# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0005_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorgjoinrequest',
            name='approvedOrRejectedBy',
        ),
        migrations.RemoveField(
            model_name='userorgjoinrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='userorgjoinrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='userorganizationrolerel',
            name='approvedOrRejectedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userorganizationrolerel',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserOrgJoinRequest',
        ),
    ]
