# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0006_auto_20170105_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('over18', models.BooleanField()),
                ('addedOn', models.DateField()),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addedDonor', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentTFR', models.FloatField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('notes', models.CharField(max_length=1024)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='form1',
            name='org',
        ),
        migrations.RemoveField(
            model_name='form1',
            name='user',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='money',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='chk',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='form',
        ),
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donationType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='recurring',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Form1',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myApp.Donors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='payTerms',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myApp.PayTerms'),
            preserve_default=False,
        ),
    ]
