# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20170105_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorganizationrolerel',
            name='join_date',
        ),
        migrations.AddField(
            model_name='userorganizationrolerel',
            name='approvedOrRejectDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userorganizationrolerel',
            name='request_date',
            field=models.DateTimeField(null=True),
        ),
    ]
