# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20170112_0718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donors',
            new_name='Donor',
        ),
    ]
