# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20170112_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payTerms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.PayTerms'),
        ),
    ]
