# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20170112_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='addedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='addedOn',
            field=models.DateTimeField(),
        ),
    ]
