# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20170112_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='formDate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
