# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 03:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_auto_20170115_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='notes',
        ),
        migrations.AlterField(
            model_name='check',
            name='proccessedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='check',
            name='processedOn',
            field=models.DateTimeField(null=True),
        ),
    ]
