# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0017_auto_20170116_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hoursType', models.IntegerField()),
                ('hours', models.FloatField()),
                ('addedOn', models.DateTimeField()),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addedHours', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
