# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0018_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payterms',
            old_name='percentTFR',
            new_name='percent',
        ),
        migrations.AddField(
            model_name='payterms',
            name='addedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payTermsAdder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payterms',
            name='addedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payterms',
            name='termsType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payterms',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='payterms',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payterms',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='payterms',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
