# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0020_orgsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='addedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgSettingsChanger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='addedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
