# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_auto_20170127_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctransaction',
            name='donation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ccTransaction', to='myApp.Donation'),
            preserve_default=False,
        ),
    ]
