# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_cctransaction_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='addr',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='zipcode',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
