# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0023_auto_20170228_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proccessedOn', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('fee', models.FloatField()),
                ('notes', models.CharField(max_length=128)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Donation')),
                ('proccessedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cctransaction',
            name='creditCard',
        ),
        migrations.RemoveField(
            model_name='cctransaction',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='cctransaction',
            name='proccessedBy',
        ),
        migrations.DeleteModel(
            name='CCTransaction',
        ),
    ]
