# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_auto_20170413_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.Donation'),
        ),
    ]
