# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0029_reimbursementrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('reviewedOn', models.DateField()),
                ('respondedOn', models.DateTimeField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.ReimbursementRequest')),
                ('respondedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursementResponder', to=settings.AUTH_USER_MODEL)),
                ('reviewedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
