# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_reimbursementresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementresponse',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.ReimbursementRequest'),
        ),
    ]
