# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_auto_20170524_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimbursementrequest',
            old_name='worker',
            new_name='workerId',
        ),
    ]
