# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-06 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0034_invoice_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='addr',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
