# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0036_managerworkerrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerworkerrel',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.Organization'),
            preserve_default=False,
        ),
    ]
