# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-25 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0038_auto_20170925_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerworkerrel',
            old_name='organization',
            new_name='org',
        ),
    ]
