# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-25 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0039_auto_20170925_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerworkerrel',
            name='assignedOn',
            field=models.DateTimeField(),
        ),
    ]
