# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-29 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0040_auto_20170925_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursType', models.IntegerField()),
                ('rate', models.FloatField()),
                ('startDate', models.DateField()),
                ('setOn', models.DateTimeField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Organization')),
                ('setBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
