# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-29 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0041_payrates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayRates',
            new_name='PayRate',
        ),
    ]
